### PR TITLE
Upstream merge

### PR DESCRIPTION
**Pull request by willrlin**
## Issue

- Addresses #293

## Description

Upstream merge from November 29.

## How Can This Be Tested/Reviewed?

Run tests, click around on the site and ensure things work.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have updated the changelog to include a description of my changes
- [ ] I have run `yarn generate:client` if I made backend changes
- [ ] I have exported any new pieces in ui-components

### CODE REVIEW

**Comment by willrlin** [comment]
I'm still fixing some tests and clicking around the site to make sure things aren't broken, but you can start reviewing.

**Comment by anders-schneider** [comment]
I'm getting an error with the JurisdictionService when I try to navigate to localhost:3000/listings:

```
 BACKEND_CORE {
 BACKEND_CORE   message: 'Not Found',
 BACKEND_CORE   stack: 'Error: Not Found\n' +
 BACKEND_CORE     '    at JurisdictionsService.findOne (/Users/aeschneider/Documents/GitHub/bloom/backend/core/dist/src/jurisdictions/services/jurisdictions.service.js:43:19)\n' +
 BACKEND_CORE     '    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n' +
 BACKEND_CORE     '    at async JurisdictionsController.retrieveByName (/Users/aeschneider/Documents/GitHub/bloom/backend/core/dist/src/jurisdictions/jurisdictions.controller.js:45:66)',
 BACKEND_CORE   exception: NotFoundException [Error]: Not Found
 BACKEND_CORE       at JurisdictionsService.findOne (/Users/aeschneider/Documents/GitHub/bloom/backend/core/dist/src/jurisdictions/services/jurisdictions.service.js:43:19)
 BACKEND_CORE       at processTicksAndRejections (internal/process/task_queues.js:95:5)
 BACKEND_CORE       at async JurisdictionsController.retrieveByName (/Users/aeschneider/Documents/GitHub/bloom/backend/core/dist/src/jurisdictions/jurisdictions.controller.js:45:66) {
 BACKEND_CORE     response: { statusCode: 404, message: 'Not Found' },
 BACKEND_CORE     status: 404
 BACKEND_CORE   }
 BACKEND_CORE }
 ```

That's after a yarn db:reseed, and making sure that my backend/core/.env is up-to-date with the template. Could there be something else I'm missing?

**Comment by willrlin** [comment]
> That's after a yarn db:reseed, and making sure that my backend/core/.env is up-to-date with the template. Could there be something else I'm missing?
Do you have `JURISDICTION_NAME=Detroit` set in your `sites/public/.env`?

**Comment by anders-schneider** [comment]
> > That's after a yarn db:reseed, and making sure that my backend/core/.env is up-to-date with the template. Could there be something else I'm missing?
> 
> Do you have `JURISDICTION_NAME=Detroit` set in your `sites/public/.env`?

🤦  thanks, now I do!

Now I'm running into a `Filter Not Implemented` error when I try to go localhost:3000/listings - it seems to happen when I don't add any filter (localhost:3000/listings) and when I add any filter (e.g. http://localhost:3000/listings/filtered?page=1&oneBdrm=true&twoBdrm=true). Do you know anything about that?

**Comment by plunkettgoogle** [comment]
When I do the following:

```
cd backend/core
git checkout main
yarn db:reseed:detroit
git checkout origin/upstream-merge
yarn db:migration:run
```

I get the following error:

```
Error during migration run:
TypeError: Cannot read property 'id' of undefined
    at addJurisdictionalEmailSignatures1635546032998.up (/usr/local/google/home/patplunkett/bloom/backend/core/src/migration/1635546032998-add-jurisdictional-email-signatures.ts:11:18)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

It seems to be tripping up on a missing `San Jose` jurisdiction. Might need to modify the migration script to either ignore, or insert that jurisdiction into the database.

**Comment by plunkettgoogle** [comment]
The text on the centered logo is line wrapped now:

localhost_3000_

**Comment by plunkettgoogle** [comment]
> 



> > > That's after a yarn db:reseed, and making sure that my backend/core/.env is up-to-date with the template. Could there be something else I'm missing?
> > 
> > 
> > Do you have `JURISDICTION_NAME=Detroit` set in your `sites/public/.env`?
> 
> facepalm thanks, now I do!
> 
> Now I'm running into a `Filter Not Implemented` error when I try to go localhost:3000/listings - it seems to happen when I don't add any filter (localhost:3000/listings) and when I add any filter (e.g. http://localhost:3000/listings/filtered?page=1&oneBdrm=true&twoBdrm=true). Do you know anything about that?

It looks like they removed the `include_nulls` filter upstream (https://github.com/bloom-housing/bloom/pull/1984), so we need to add back the `if (filterKey === "$include_nulls")` check on line 50 of `backend/core/src/shared/filter/index.ts`

**Comment by willrlin** [comment]
Sorry for unnecessary churn! I had some fixes locally that I did not push up. I think you're going to have to drop the db and reseed from HEAD after this because I had to re-add SanJose as a jurisdiction to the one of the previous migrations (matching upstream).

**Comment by willrlin** [comment]
Note: this is still rough cut, I'm actively working on fixing things but I thought it would help to start looking at the changes involved.

**Comment by plunkettgoogle** [comment]
> Sorry for unnecessary churn! I had some fixes locally that I did not push up. I think you're going to have to drop the db and reseed from HEAD after this because I had to re-add SanJose as a jurisdiction to the one of the previous migrations (matching upstream).

How will we handle that in the deployment (once it's fixed, that is)? Is it possible to re-seed the db on the deployment? Is that something we want to do?

**Comment by willrlin** [comment]
> How will we handle that in the deployment (once it's fixed, that is)? Is it possible to re-seed the db on the deployment? Is that something we want to do?

The deployment is just using `yarn db:reseed:detroit` data AFAIK (unless someone imported the full dataset, but doesn't look like it from the deployed site). So it's fine to reseed it. Future maintainers will have to be careful about the migrations going forward if the deployed databases don't include certain jurisdictions. We should also give that feedback to Exygy upstream.

**Pull request closed without merging**
