### PR TITLE
feat: add new hero image

### LINKED ISSUE #1251: Detroit - Update homepage hero
Update the Detroit hero image to a higher res one 

https://drive.google.com/file/d/15oyyERWKiyjE75T_SimWKV07snIoY_ZP/view?usp=sharing

### PR DESCRIPTION
**Pull request by adriencyberspace**
## Issue #1251 

- Closes #1251
- Addresses #issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

This replaces the hometown hero page with a higher resolution image. NOTE: the original file size was over 35MB and I optimized it down to 2.5MB. Let me know if that's still too big or if we want some of the resolution back.

## How Can This Be Tested/Reviewed?

Entry Point: http://localhost:3000/

The hero image should be the updated one:
image

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [x] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [x] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Review by emilyjablonski — CHANGES_REQUESTED** [review]
It looks like the photo was removed, and the new one wasn't added? At the moment it doesn't render an image

**Comment by adriencyberspace** [comment]
@emilyjablonski needed to manually track it for some reason. Try again? Thanks!

**Comment by jaredcwhite** [comment]
@adriencyberspace Could we get it under 1MB I wonder? Might just need to bump up JPG compression a bit more, hopefully without looking too blocky.

**Review by emilyjablonski — APPROVED** [review]

**Comment by adriencyberspace** [comment]
@jaredcwhite got it down to 620kb

**Pull request merged**
