### PR TITLE
feat: Add .5 and 1.5 bathroom options to min and max dropdown in Add …

### PR DESCRIPTION
**Pull request by adriencyberspace**
…Unit Group

## Issue #1106

- Addresses #1106 
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

This adds .5 and 1.5 bathroom options to the min and max bathroom dropdowns in Add Unit Group. I created a new bathroomOptions array of objects in UnitsSummaryForm to use for both min and max dropdowns, since our numberOptions helper only increments whole integers.

## How Can This Be Tested/Reviewed?

In New Listing, enter the Add Unit Group form. The min and max bathroom dropdowns now have .5 and 1.5 options in addition to integers 1-10.

No tests.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Comment by adriencyberspace** [comment]
@kathyccheng I noticed that bloom core only has the option for max 5 bathrooms. Wondering if you want me to change Detroit to max 5 as well, while we're here.

**Comment by kathyccheng** [comment]
yeah that probably makes sense!

**Review by emilyjablonski — CHANGES_REQUESTED** [review]
I'm getting a 500 internal server error (`invalid input syntax for type integer: "0.5"\n`) when I try to save with `.5` baths. I imagine it might be a type issue, either sending a string and expecting a number, or if that backend field only allows integers.

**Comment by emilyjablonski** [comment]
@YazeedLoonat I pushed commits to this so I'd like to not be a reviewer as a heads up

**Review by seanmalbert — APPROVED** [review]

**Comment by seanmalbert** [comment]
This looks good to me. @emilyjablonski , you'll need to approve it before it can be merged.

**Review by emilyjablonski — APPROVED** [review]

**Pull request merged**
