### PR TITLE
337/add detroit ami data

### LINKED ISSUE #337: Add Detroit AMI chart data
TODO: this ticket needs scoping now that we have some more information about property manager data.

There is an ami_chart and ami_chart_item table in the database where we need to add the Detroit specific data.

We also need to [seed the Detroit AMI data](https://github.com/CityOfDetroit/bloom/tree/main/backend/core/src/seeds/ami-charts) for local development.

### PR DESCRIPTION
**Pull request by willrlin**
## Issue

- Closes #337

## Description

Create a bash script that generates AMI chart data in Typescript from a text file that matches the PDF format that MSHDA publishes.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Can This Be Tested/Reviewed?

I ran the script with the text file as input, then manually verified a few values. I then seeded the database and checked that the Detroit AMI chart was in the ami_chart database.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [x] I have reviewed the changes in a mobile view
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have assigned reviewers
- [x] I have updated the changelog to include a description of my changes

### CODE REVIEW

**Review by anders-schneider — APPROVED** [review]
I wouldn't trust my ability to review your bash script (looks like magic to me), but I ran it and it successfully regenerated the `.ts` file with all the correct JSON, so LGTM! :)

**Comment by elenm** [comment]
I see that we're not populating the ami_chart_item table. Is that intentional? Does Bloom also leave that table empty in their implementations?

**Comment by anders-schneider** [comment]
> I see that we're not populating the ami_chart_item table. Is that intentional? Does Bloom also leave that table empty in their implementations?

I think we should be populating ami_chart_item (https://github.com/CityOfDetroit/bloom/blob/af80da7f8b873a1d3117df8a116733b558e40b69/backend/core/src/seeds/ami-charts/WayneCountyMSHDA2021.ts#L7), unless that part of this isn't working?

**Comment by willrlin** [comment]
The way the seeder works does not populate the ami_chart_item AFAICT; those "items" just get store directly in the chart column "items". I was copying what Exygy had (bloom doesn't populate the ami_chart_item).

**Pull request merged**
