### PR TITLE
Upstream merge 8/4

### PR DESCRIPTION
**Pull request by willrlin**
## Issue

Addresses #293 

## Description

Merge from upstream/dev.

## Type of change

Upstream merge

## How Can This Be Tested/Reviewed?

Passing tests and walkthrough of local site.

- [x] Desktop View
- [x] Mobile View

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [x] I have reviewed the changes in a mobile view
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have assigned reviewers
- [x] I have updated the changelog to include a description of my changes

### CODE REVIEW

**Comment by willrlin** [comment]
This may be an easier way to review: https://github.com/bloom-housing/bloom/compare/dev...CityOfDetroit:upstream-merge

**Comment by willrlin** [comment]
@abbiefarr the UnitsSummarized table in editing in the partner view seems to be flipped from what I was expecting (and I'm working on fixing it). Could you review to make sure I didn't miss anything else?

**Comment by abbiefarr** [comment]
Hm, wrt the unit summary view in listing edit, for some reason it seems like the initial value in the form isn't being set correctly. It toggles whenever you click the button, which is correct, but one of the radio buttons should be populated when the form is rendered, and it isn't. Trying to figure out why.

**Review by abbiefarr — APPROVED** [review]
I'm so befuddled by this new issue where the default radio button isn't selected... I'll file a bug for it and look into it at some point.

**Pull request merged**
