### PR TITLE
Add unit tests for the remaining eligibility questionnaire React components

### LINKED ISSUE #219: [Eligibility Questionnaire] Add tests
Add unit tests for the questionnaire.

### PR DESCRIPTION
**Pull request by anders-schneider**
## Issue

- Closes #219

## Description

This change adds tests for the three eligibility questionnaire React components that previously didn't have them. These tests primarily test that (a) error messages display and disappear appropriately and (b) the router maintains the correct state.

The changes to`yarn.lock` and `sites/public/package.json` came from adding two testing libraries with `yarn add --dev @testing-library/user-event @testing-library/dom`.

## Type of change

- [X] Adds test coverage

## How Can This Be Tested/Reviewed?

`cd sites/public && yarn test:unit-tests`

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have updated the changelog to include a description of my changes
- [ ] I have run `yarn generate:client` if I made backend changes

### CODE REVIEW

**Review by willrlin — APPROVED** [review]
Please confirm that Travis is running these new tests before submitting.

**Comment by anders-schneider** [comment]
@willrlin Some of the `yarn.lock` and `sites/public/package.json` changes appear unrelated - thoughts on whether I should revert those?

**Comment by anders-schneider** [comment]
> Please confirm that Travis is running these new tests before submitting.

Confirmed!

image

**Comment by willrlin** [comment]
I think it's ok to leave them. I'd rather keep it in sync with what yarn would generate anyway.

**Pull request merged**
