### PR TITLE
Upstream merge 7/28

### PR DESCRIPTION
**Pull request by willrlin**
Linked to #293

### CODE REVIEW

**Comment by willrlin** [comment]
For an easier comparison, check the diffs of this branch vs. upstream/dev: https://github.com/bloom-housing/bloom/compare/dev...CityOfDetroit:upstream-merge

**Comment by willrlin** [comment]
I checked every file carefully myself using this diff view as well as the diff view in the comment above. @abbiefarr @avaleske could you double check the changes to classes relevant for filtering?

Also to note: all the changes in backend/core/migrations and most of the backend-swagger.ts changes are formatting only.

**Review by abbiefarr — APPROVED** [review]
LGTM, I glanced at the files related to filtering and they looked fine (I didn't look too hard). Mainly I fetched your branch and tested that filtering still worked correctly.

**Comment by willrlin** [comment]
Thanks for the review!

**Pull request merged**
