### PR TITLE
fix: show all listings button labels

### PR DESCRIPTION
**Pull request by KrissDrawing**
# Pull Request Template

## Issue Overview

This PR addresses #1543 

- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description
Changed label of reset button to 'reset'. Added aria-label to filter button.
Removed obsolete translations from used keys.

## How Can This Be Tested/Reviewed?

go to listings page, turn on screen reader. Check filter button without filters + after picking some filters, and reset button.

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [x] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Review by emilyjablonski — APPROVED** [review]
LGTM apart from the two missing Spanish translations for `Reset` and `Filter` which might be known / not available?

**Review by ColinBuyck — COMMENTED** [review]
This is working well! Just one question. I'm noticing that the issue references the language of "restart" rather than "reset". I personally prefer your wording but still wanted to call that out in case that is a strict request. Any thoughts here @sarahlazarich or @eajensenwa?

**Comment by sarahlazarich** [comment]
@ColinBuyck I don't think that's a strict requirement, we should we ok! Thanks for checking in.

**Review by ColinBuyck — APPROVED** [review]
LGTM once Emily's translation question is addressed 🏟️

**Comment by sarahlazarich** [comment]
I'm sorry I missed that question! I google translated for those, and the responses are here. 

Reset: 
- Spanish: Reinicializar
- Arabic: إعادة ضبط
- Bengali: রিসেট

Filter: 
- Spanish: filtrar
- Arabic: صفى
- Bengali: ফিল্টার

**Pull request merged**
