### PR TITLE
Upstream merge 8/19

### PR DESCRIPTION
**Pull request by willrlin**
# Pull Request Template

## Issue

Addresses #293

## Description

Upstream merge 8/19, includes updates to the unit summary table and listing views.

## How Can This Be Tested/Reviewed?

Passing unit tests; I also compiled and viewed the sites and clicked around.

- [x] Desktop View
- [x] Mobile View
- [x] UI unit tests
- [x] Backend unit tests
- [x] Backend e2e tests

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [x] I have reviewed the changes in a mobile view
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have assigned reviewers
- [x] I have updated the changelog to include a description of my changes

### CODE REVIEW

**Comment by abbiefarr** [comment]
I'm trying to run the import script from your branch but I'm getting this error:
`column User.is_admin does not exist`

Haven't root caused yet.

**Comment by abbiefarr** [comment]
Huh, ignore my last comment, I tried it again and it magically started working ¯\_(ツ)_/¯

**Review by abbiefarr — APPROVED** [review]
The test failure is fixed in https://github.com/bloom-housing/bloom/pull/1692

Can you pull that in or delete the line?

**Comment by willrlin** [comment]
Thanks, I fixed it locally but was waiting to see if you had any other comments to address before pushing the commit.

**Pull request merged**
