### PR TITLE
1373/housing basics page

### PR DESCRIPTION
**Pull request by ColinBuyck**
# Pull Request Template

## Issue Overview

This PR addresses #1373

- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

This PR brings over the media card, video component, and updated modal and implements them on the new housing-basics page. It also updates the action blocks at the bottom of the home page to include a new section and updated icons so that all three icons are aligned.

## How Can This Be Tested/Reviewed?

This PR can be tested on Detroit Public's site. After arriving at the homepage, scroll down to the action blocks and ensure the new section is correct and the three sections are aligned. Then click learn more and test out the functionality of the media cards by clicking on the title or any part of the green header on the card. After you've tested viewing the video, ensure the modal can be closed and others cards opened.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1202653933913055

### CODE REVIEW

**Comment by jaredcwhite** [comment]
Looking good @ColinBuyck. I noticed one issue on iOS Safari with the play icon:

219C8231-F7F1-4BB1-BA32-690291C458FB

The other icons look good though.

**Review by jaredcwhite — CHANGES_REQUESTED** [review]
(forgot to use the review button)

**Comment by ColinBuyck** [comment]
Great catch @jaredcwhite! It should be fixed now but just unsure on if there is a cleaner way.

**Comment by emilyjablonski** [comment]
This looks so good! I have two quick questions: (1) in terms of accessibility, when I use keyboard navigation through the media grid I hit the action for opening the modal twice, and once it is visually hidden for the icon and the second time the focus state is visible on the title, we likely only want one of those to be focusable through the keyboard @slowbot do you have a preference? (2) I can't find links to the exact copy and videos used in the issue do you mind commenting those?

**Comment by ColinBuyck** [comment]
Here is the link @emilyjablonski: https://docs.google.com/spreadsheets/d/1glJRJ6znXsYJwF2AAI0w6xhN59ebcEMO8Qr0JU2mLnU/edit#gid=197107808. Also talked to Jesse, and going to bring over the full Core modal for this so WIP for the time being.

**Review by emilyjablonski — CHANGES_REQUESTED** [review]
Content & a11y looks great. In terms of bringing over the full modal, something I'm seeing is that the font of the title here doesn't match the design, it looks like the Figma has the font as the default font in core

Screen Shot 2022-07-29 at 7 27 25 PM

**Comment by ColinBuyck** [comment]
@slowbot Thanks! The PR should reflect those updates now if you have the chance to give it a look.

**Review by emilyjablonski — APPROVED** [review]

**Pull request merged**
