### PR TITLE
fix: region and variable naming update

### LINKED ISSUE #1296: Detroit - Update Regions
Notes
* Drop Midtown 
* Rename Downtown to Greater Downtown 
* This should be updated on Homepage, Filters, and Partners Portal Region Dropdown

### PR DESCRIPTION
**Pull request by ColinBuyck**
## Issue

- Closes #1296 

This issue involved changing 'Downtown' to 'Greater Downtown', and removing 'Midtown' from the site. Since the naming and region options were directly linked with the search params, I decided to make these adjustments in the variable names and backend files so that it could maintain the approach to search and filtering it had before.

This can be tested in three main areas. On the Detroit public site, verify that the region cards on the home page do not show "Midtown" and show "Greater Downtown". Then, navigate to the list of rentals and open the filtering drawer. In the dropdown for region you should see the two adjustments mentioned above. 

Lastly, navigate to the partner's portal and begin creating a new listing. From there, you should see the updated region information in the dropdown.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Comment by emilyjablonski** [comment]
@ColinBuyck Sorry I think I just gave you merge conflicts here 😅

**Comment by ColinBuyck** [comment]
They should be resolved now! Only thing I am still wondering is about the backend changes made to reflect the new wording. I figured it would be helpful to ensure consistency across the app rather than have conditionals to change 'Greater Downtown' to 'Downtown' for values, but unsure if there would be unintended consequences.

**Review by emilyjablonski — CHANGES_REQUESTED** [review]
Need an update to the migration file - lmk if you have any questions!

**Review by seanmalbert — APPROVED** [review]
looks good!

**Review by emilyjablonski — APPROVED** [review]

**Pull request merged**
