### PR TITLE
feat: exposing leasing company website

### PR DESCRIPTION
**Pull request by YazeedLoonat**
- Closes [#issue](https://github.com/CityOfDetroit/bloom/issues/1056)

## Description
This exposes the leasing agent's company website field on the partners side

## How Can This Be Tested/Reviewed?
Log in to the partner's site as an admin user
go to create a new listing
fill out all the info, including the newly exposed `Company Website` field
save the listing
verify the listing details page on the partner's side expose that information
go in and edit the listing, and verify that the company website info is there and available and its possible to change that info

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [x] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [x] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [x] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Comment by YazeedLoonat** [comment]
Hey @emilyjablonski this is ready for you to peep again

**Review by emilyjablonski — APPROVED** [review]

**Review by seanmalbert — CHANGES_REQUESTED** [review]
@YazeedLoonat ,

We need this field to have URL validation. The @isUrl decorator should also be added after the @isString decorator on the backend for the `managementWebsite` field. It appears that NestJs uses [validator](https://www.npmjs.com/package/validator) for its validation, so you can pull in the same package in partners for consistency.

**Comment by emilyjablonski** [comment]
We might want to make a ticket to add the same validator to other URL fields like the custom app URL

**Comment by YazeedLoonat** [comment]
Hey @seanmalbert this is ready for re-review

**Comment by YazeedLoonat** [comment]
Hey @seanmalbert this should be ready for your 👀 again

**Review by seanmalbert — APPROVED** [review]

**Pull request merged**
