### PR TITLE
Build the production site for Cypress tests.

### PR DESCRIPTION
**Pull request by willrlin**
In #593 I noticed that building the production site actually sped up the overall time for Cypress tests in Travis because the production site responds faster (see the difference between the partner Cypress tests with production build and the public Cypress tests with dev build [here](https://app.travis-ci.com/github/CityOfDetroit/bloom/builds/238135030)). So, apply the same to the public site.

### CODE REVIEW

**Comment by abbiefarr** [comment]
Is the partner build timing out because it's trying to restore a cache that's way too large? I can't really tell from the output logs.

**Comment by willrlin** [comment]
That's a good question - I can't tell either; it could be?

**Comment by abbiefarr** [comment]
This thread may be useful: https://github.com/travis-ci/travis-ci/issues/10113

It suggests we clean the cache and rebuild.

**Comment by willrlin** [comment]
Maybe it was just a transient failure - it only happened that one time on this branch (and after merging with main again it passed).

**Review by abbiefarr — APPROVED** [review]

**Pull request merged**
