### PR TITLE
1486/listing finder refactor

### PR DESCRIPTION
**Pull request by ColinBuyck**
# Pull Request Template

## Issue Overview

This PR addresses #1486 along with the QA notes left on #1433.

- [x] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

This PR incorporates the new ButtonGroup, HeadingGroup, and Card components into the rental finder. 

## How Can This Be Tested/Reviewed?

This can be tested by verifying that the finder continues to match the Figma designs (ie those linked in #1433 and reflects the updated mobile notes seen in the QA notes of the same issue.
## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have added QA notes to the issue with applicable URLs
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [x] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Review by emilyjablonski — APPROVED** [review]
LGTM! Only note is that I'm seeing some missing translations on the programs section. These strings are also missing on the listing directory filter drawer, so I don't think it originated here. Makes sense to me to handle that separately unless it seems like an easy fix or is a blocker to release.
Screen Shot 2022-11-10 at 5 45 35 PM

**Review by ludtkemorgan — APPROVED** [review]
🥇

**Comment by ColinBuyck** [comment]
@emilyjablonski Thank you for the review! As for the translation keys, I was only able to reproduce that issue locally when the db was reseeded using "yarn db:reseed" rather than "yarn db:reseed:detroit". Let me know if that fixes things on your side!

**Comment by emilyjablonski** [comment]
@ColinBuyck Ah yes it does! And that data set seems to match dev/prod. LGTM, we should clean up both calls later 👍

**Pull request merged**
