### PR TITLE
Upstream merge 9/9

### PR DESCRIPTION
**Pull request by willrlin**
## Issue

- Addresses #293

## Description

Upstream merge from 9/9; contains fewer commits for easier review than #563.

## How Can This Be Tested/Reviewed?

Clicked around the site. Tried to add/edit listings (note: there is still the known issue of the format of the monthlyRentMin and amiPercentage).

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [x] I have reviewed the changes in a mobile view
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have assigned reviewers
- [x] I have updated the changelog to include a description of my changes
- [x] I have run `yarn generate:client` if I made backend changes

### CODE REVIEW

**Review by abbiefarr — COMMENTED** [review]
* Filter state doesn't persist after being applied. I verified that this isn't currently happening in the deployed version.
* The availability filter doesn't play nice with the other filters. This is happening on the deployed site too. I filed #574 for this.

**Comment by willrlin** [comment]
I fixed the filter state issue; this was caused by changes in `Select.tsx`. I'll attempt to contribute my fixes upstream so the next merge it will be in sync.

**Review by abbiefarr — COMMENTED** [review]
The `Select` changes may be causing this weird default behavior in the partner portal when you add a summary or a unit entry. Previously (and in the deployed site) the field name is the default option shown.

image

**Comment by willrlin** [comment]
Fixed the Select issue.

**Review by abbiefarr — APPROVED** [review]

**Pull request merged**
